version: '3'

services:
  nmrr:
    build: ./web
    restart: always
    ports:
      - "8000"
    depends_on:
      - db_mongo
      - redis
      - db_psql
    volumes:
      - ./settings.py:/srv/mgi-nmrr/nmrr/settings.py
    environment:
      - DJANGO_SETTINGS_MODULE=nmrr.settings
    networks:
      nmrr_network:
        aliases:
          - nmrr    

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      nmrr_network:
        aliases:
          - nginx
  
  db_mongo:
    image: mongo:3.4
    restart: always
    ports:
      - "27017"
    volumes:
      - mongo-data:/data/db/
      - ./db/set_mongodb_password.sh:/set_mongodb_password.sh
    environment:
      - MONGODB_ADMIN=admin
      - MONGODB_ADMIN_PASS=admin
      - MONGODB_USER=mgi_user
      - MONGODB_PASSWORD=mgi_password
    networks:
      nmrr_network:
        aliases:
          - db_mongo

  db_client:
    image: mongo:3.4
    depends_on: 
      - db_mongo
    ports:
      - "27017"
    volumes:
      - ./db/set_mongodb_password.sh:/set_mongodb_password.sh
    entrypoint: []
    command: bash -c "/set_mongodb_password.sh"
    networks:
      nmrr_network:
        aliases:
          - db_client

  redis:
    image: redis:5
    restart: always
    ports:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      nmrr_network:
        aliases:
          - redis

  db_psql:
    image: postgres:latest
    restart: always
    ports:
      - "5432"
    volumes:
      - psql-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mgi_user
      - POSTGRES_PASSWORD=mgi_password
      - POSTGRES_DB=mgi
    networks:
      nmrr_network:
        aliases:
          - psql

volumes:
  mongo-data:
  redis-data:
  psql-data:

networks:
  nmrr_network:
    driver: bridge    
